<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Inexdigital\Centrifugo\Grpc\Centrifugal\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>centrifugal.centrifugo.api.PublishResponse</code>
 */
class PublishResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.PublishResult result = 2;</code>
     */
    protected $result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\Error $error
     *     @type \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\PublishResult $result
     * }
     */
    public function __construct($data = NULL) {
        \Inexdigital\Centrifugo\Grpc\Centrifugal\GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Error error = 1;</code>
     * @return \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.Error error = 1;</code>
     * @param \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.PublishResult result = 2;</code>
     * @return \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\PublishResult|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.centrifugal.centrifugo.api.PublishResult result = 2;</code>
     * @param \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\PublishResult $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Inexdigital\Centrifugo\Grpc\Centrifugal\Api\PublishResult::class);
        $this->result = $var;

        return $this;
    }

}

